project:
  type: website

website:
  title: "kbhsec_website"
  favicon: "KbhSec_Logo_favicon.png"
  navbar:
    title: "kbhsec.dk"
    left:
      - text: Home
        href: index.qmd
      - text: About KbhSec
        href: about.qmd
format:
  html:
    theme: slate
    css: styles.css
    toc: true

render:
  - "*.qmd"
  - "!README.md"

execute:
  freeze: auto

resources:
  - CNAME
